### ISSUE TITLE
The version uploaded to the plugins directory ships with the vendor folder

### ISSUE THREAD

**Issue by mudrd8mz** [hitteshahuja/filter_bath_https_monitor#1]
The version of the filter that has been uploaded to the plugins directory comes with some other vendors' libraries and scripts attached (squizlabs, phpcs, ...). That does not seem valid as those are probably useful just for development.

**Comment by hitteshahuja** [comment]
Good point. Ill remove the vendor folder from the zip file. Thanks

**Comment by hitteshahuja** [comment]
done. upload a newer version that removed the vendor/ folder and incorporates the changes discussed in #2 and #3

**Comment by mudrd8mz** [comment]
Looks fixed now thanks.
